variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  PNPM_VERSION: 10.0.0

stages:
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store
  policy: pull-push

.default_before_script: &default_before_script
  - npm install -g pnpm@${PNPM_VERSION}
  - pnpm config set onlyBuiltDependencies false
  - pnpm install --store=.pnpm-store --no-frozen-lockfile
test:
  stage: test
  image: node:20-alpine
  before_script:
    - *default_before_script
    - pnpm install --no-frozen-lockfile  # Remove frozen-lockfile check

  script:
    - pnpm lint
    - pnpm test:ci
    - pnpm build
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week

build:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker buildx build \
        --platform linux/amd64 \
        --build-arg NODE_ENV=production \
        --build-arg MONGO_URI=$MONGO_URI \
        --build-arg JWT_SECRET=$JWT_SECRET \
        --build-arg EMAIL_USER=$EMAIL_USER \
        --build-arg SENDGRID_API_KEY=$SENDGRID_API_KEY \
        -t ${IMAGE_TAG} \
        -t ${CI_REGISTRY_IMAGE}:latest \
        .
    - docker push ${IMAGE_TAG}
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - main

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - |
      kubectl set env deployment/your-deployment \
        MONGO_URI=${MONGO_URI} \
        JWT_SECRET=${JWT_SECRET} \
        EMAIL_USER=${EMAIL_USER} \
        SENDGRID_API_KEY=${SENDGRID_API_KEY}
    - kubectl set image deployment/your-deployment your-container=${IMAGE_TAG}
  only:
    - main
  when: manual
