import { model, models, Schema } from 'mongoose';

const machineSessionSchema = new Schema(
  {
    _id: { type: String },
    avgBet: { type: Number, default: 0 },
    billsIn: { type: Number, default: 0 },
    createdAt: { type: Date },
    endBillMeters: {
      _id: { type: String },
      machineSession: { type: String },
      machine: { type: String },
      location: { type: String },
      movement: {
        dollar1: { type: Number },
        dollar2: { type: Number },
        dollar5: { type: Number },
        dollar10: { type: Number },
        dollar20: { type: Number },
        dollar50: { type: Number },
        dollar100: { type: Number },
        dollar500: { type: Number },
        dollar1000: { type: Number },
        dollar2000: { type: Number },
        dollar5000: { type: Number },
        dollarTotal: { type: Number },
        dollarTotalUnknown: { type: Number },
      },
      dollar1: { type: Number },
      dollar2: { type: Number },
      dollar5: { type: Number },
      dollar10: { type: Number },
      dollar20: { type: Number },
      dollar50: { type: Number },
      dollar100: { type: Number },
      dollar500: { type: Number },
      dollar1000: { type: Number },
      dollar2000: { type: Number },
      dollar5000: { type: Number },
      dollarTotal: { type: Number },
      dollarTotalUnknown: { type: Number },
      readAt: { type: Date },
      createdAt: { type: Date },
      updatedAt: { type: Date },
    },
    endMeters: {
      _id: { type: String },
      machine: { type: String },
      location: { type: String },
      movement: {
        coinIn: { type: Number },
        coinOut: { type: Number },
        jackpot: { type: Number },
        totalHandPaidCancelledCredits: { type: Number },
        totalCancelledCredits: { type: Number },
        gamesPlayed: { type: Number },
        gamesWon: { type: Number },
        currentCredits: { type: Number },
        totalWonCredits: { type: Number },
        drop: { type: Number },
      },
      coinIn: { type: Number },
      coinOut: { type: Number },
      jackpot: { type: Number },
      totalHandPaidCancelledCredits: { type: Number },
      totalCancelledCredits: { type: Number },
      gamesPlayed: { type: Number },
      gamesWon: { type: Number },
      currentCredits: { type: Number },
      totalWonCredits: { type: Number },
      drop: { type: Number },
      readAt: { type: Date },
      createdAt: { type: Date },
      updatedAt: { type: Date },
    },
    endTime: { type: Date },
    gameName: { type: String, default: '' },
    gamesPlayed: { type: Number, default: 0 },
    gamesWon: { type: Number, default: 0 },
    lastAutoLogoutTime: { type: Date },
    intermediateMeters: {
      _id: { type: String },
      machine: { type: String },
      location: { type: String },
      movement: {
        coinIn: { type: Number },
        coinOut: { type: Number },
        jackpot: { type: Number },
        totalHandPaidCancelledCredits: { type: Number },
        totalCancelledCredits: { type: Number },
        gamesPlayed: { type: Number },
        gamesWon: { type: Number },
        currentCredits: { type: Number },
        totalWonCredits: { type: Number },
        drop: { type: Number },
      },
      coinIn: { type: Number },
      coinOut: { type: Number },
      jackpot: { type: Number },
      totalHandPaidCancelledCredits: { type: Number },
      totalCancelledCredits: { type: Number },
      gamesPlayed: { type: Number },
      gamesWon: { type: Number },
      currentCredits: { type: Number },
      totalWonCredits: { type: Number },
      drop: { type: Number },
      readAt: { type: Date },
      createdAt: { type: Date },
      updatedAt: { type: Date },
    },
    locationMembershipSettings: {
      locationLimit: { type: Number },
      freePlayAmount: { type: Number },
      enablePoints: { type: Boolean },
      enableFreePlays: { type: Boolean },
      pointsRatioMethod: { type: String },
      pointMethodValue: { type: Number },
      gamesPlayedRatio: { type: Number },
      pointsMethodGameTypes: [{ type: String }],
      freePlayGameTypes: [{ type: String }],
      freePlayCreditsTimeout: { type: Number },
    },
    machineId: { type: String, required: true },
    machineSerialNumber: { type: String, default: '' },
    memberId: { type: String, required: true },
    nonRestricted: { type: Number, default: 0 },
    points: { type: Number, default: 0 },
    relayId: { type: String },
    restricted: { type: Number, default: 0 },
    startBillMeters: {
      _id: { type: String },
      machineSession: { type: String },
      machine: { type: String },
      location: { type: String },
      movement: {
        dollar1: { type: Number },
        dollar2: { type: Number },
        dollar5: { type: Number },
        dollar10: { type: Number },
        dollar20: { type: Number },
        dollar50: { type: Number },
        dollar100: { type: Number },
        dollar500: { type: Number },
        dollar1000: { type: Number },
        dollar2000: { type: Number },
        dollar5000: { type: Number },
        dollarTotal: { type: Number },
        dollarTotalUnknown: { type: Number },
      },
      dollar1: { type: Number },
      dollar2: { type: Number },
      dollar5: { type: Number },
      dollar10: { type: Number },
      dollar20: { type: Number },
      dollar50: { type: Number },
      dollar100: { type: Number },
      dollar500: { type: Number },
      dollar1000: { type: Number },
      dollar2000: { type: Number },
      dollar5000: { type: Number },
      dollarTotal: { type: Number },
      dollarTotalUnknown: { type: Number },
      readAt: { type: Date },
      createdAt: { type: Date },
      updatedAt: { type: Date },
    },
    startMeters: {
      _id: { type: String },
      machine: { type: String },
      location: { type: String },
      movement: {
        coinIn: { type: Number },
        coinOut: { type: Number },
        jackpot: { type: Number },
        totalHandPaidCancelledCredits: { type: Number },
        totalCancelledCredits: { type: Number },
        gamesPlayed: { type: Number },
        gamesWon: { type: Number },
        currentCredits: { type: Number },
        totalWonCredits: { type: Number },
        drop: { type: Number },
      },
      coinIn: { type: Number },
      coinOut: { type: Number },
      jackpot: { type: Number },
      totalHandPaidCancelledCredits: { type: Number },
      totalCancelledCredits: { type: Number },
      gamesPlayed: { type: Number },
      gamesWon: { type: Number },
      currentCredits: { type: Number },
      totalWonCredits: { type: Number },
      drop: { type: Number },
      readAt: { type: Date },
      createdAt: { type: Date },
      updatedAt: { type: Date },
    },
    startTime: { type: Date },
    status: { type: String, default: 'NOTACTIVE' },
    uaccount: { type: Number, default: 0 },
    ucardId: { type: String, default: '' },
    user: { type: String },
  },
  { timestamps: true }
);

// Indexes for better query performance
machineSessionSchema.index({ memberId: 1, startTime: -1 }); // For member-based queries
machineSessionSchema.index({ machineId: 1, startTime: -1 }); // For machine-based queries
machineSessionSchema.index({ startTime: -1 }); // For date-based queries

/**
 * Mongoose model for machine sessions, including all session data and meter readings.
 */
export const MachineSession =
  models.machinesessions || model('machinesessions', machineSessionSchema);
