import { authenticateUser } from '@/app/api/lib/helpers/auth';
import { connectDB } from '@/app/api/lib/middleware/db';
import {
  createBadRequestResponse,
  createErrorResponse,
  createServerErrorResponse,
  createSuccessResponse,
} from '@/app/api/lib/utils/apiResponse';
import { getFriendlyErrorMessage } from '@/lib/utils/auth';
import { getClientIP } from '@/lib/utils/ipAddress';
import { NextRequest } from 'next/server';

export const runtime = 'nodejs';

export async function POST(request: NextRequest) {
  const startTime = Date.now();

  try {
    await connectDB();

    const { identifier, password, rememberMe } = await request.json();

    if (!identifier || !password) {
      return createBadRequestResponse(
        'Email/username and password are required.'
      );
    }

    const looksLikeEmail = /\S+@\S+\.\S+/.test(identifier);
    const isUsername =
      typeof identifier === 'string' && identifier.trim().length >= 3;

    if (!(looksLikeEmail || isUsername)) {
      return createBadRequestResponse('Invalid identifier format.');
    }

    const ipAddress = getClientIP(request) || 'unknown';
    const userAgent = request.headers.get('user-agent') || 'unknown';

    const result = await authenticateUser(
      identifier,
      password,
      ipAddress,
      userAgent,
      rememberMe
    );

    if (!result.success) {
      return createErrorResponse(
        result.message || 'Authentication failed',
        401
      );
    }

    if (!result.token) {
      console.error('❌ No token generated by authenticateUser!');
      return createServerErrorResponse(
        'Authentication failed - no token generated'
      );
    }

    // Create response first
    const response = createSuccessResponse(
      {
        user: result.user,
        expiresAt: result.expiresAt,
        requiresPasswordUpdate: result.requiresPasswordUpdate ?? false,
        requiresProfileUpdate: result.requiresProfileUpdate ?? false,
        invalidProfileFields: result.invalidProfileFields,
        invalidProfileReasons: result.invalidProfileReasons,
      },
      'Login successful'
    );

    // Set cookies on the response
    const cookieOptions = {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax' as const,
      path: '/',
      maxAge: rememberMe ? 30 * 24 * 60 * 60 : 7 * 24 * 60 * 60, // 30 days if rememberMe, else 7 days
      // Don't set domain - let browser use default (current domain)
    };

    // Set token cookie
    response.cookies.set('token', result.token!, cookieOptions);

    if (result.refreshToken) {
      const refreshCookieOptions = {
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
        sameSite: 'lax' as const,
        path: '/',
        maxAge: rememberMe ? 30 * 24 * 60 * 60 : 7 * 24 * 60 * 60,
      };
      response.cookies.set(
        'refreshToken',
        result.refreshToken,
        refreshCookieOptions
      );
    }

    // Log cookie setting for debugging
    if (process.env.NODE_ENV === 'development') {
      const cookieHeader = response.headers.get('Set-Cookie');
      const tokenSize = result.token?.length || 0;
      const refreshTokenSize = result.refreshToken?.length || 0;
      console.log('[Login API] Cookie set on response:', {
        hasToken: !!result.token,
        hasRefreshToken: !!result.refreshToken,
        tokenSize,
        refreshTokenSize,
        maxAge: cookieOptions.maxAge,
        sameSite: cookieOptions.sameSite,
        secure: cookieOptions.secure,
        cookieHeader: cookieHeader?.substring(0, 200) + '...', // Truncate for readability
      });
    }

    const duration = Date.now() - startTime;
    if (duration > 1000) {
      console.warn(`[Login API] Completed in ${duration}ms`);
    }

    return response;
  } catch (error) {
    const duration = Date.now() - startTime;
    console.error(`[Login API] Error after ${duration}ms:`, error);
    return createServerErrorResponse(
      getFriendlyErrorMessage(
        error instanceof Error ? error.message : 'Login failed'
      )
    );
  }
}
