/**
 * Login API Route
 *
 * This route handles user authentication with email/username and password.
 * It supports:
 * - Email or username-based login
 * - JWT token generation and HTTP-only cookie storage
 * - Refresh token management with "remember me" option
 * - Profile and password update requirements
 * - Client IP and user agent tracking for security
 *
 * @module app/api/auth/login/route
 */

import { authenticateUser } from '@/app/api/lib/helpers/auth';
import { connectDB } from '@/app/api/lib/middleware/db';
import {
  createBadRequestResponse,
  createErrorResponse,
  createServerErrorResponse,
  createSuccessResponse,
} from '@/app/api/lib/utils/apiResponse';
import { getFriendlyErrorMessage } from '@/lib/utils/auth';
import { getClientIP } from '@/lib/utils/ipAddress';
import { NextRequest } from 'next/server';

export const runtime = 'nodejs';

/**
 * Main POST handler for user login
 *
 * Flow:
 * 1. Connect to database
 * 2. Parse and validate request body
 * 3. Validate identifier format (email or username)
 * 4. Extract client information (IP, user agent)
 * 5. Authenticate user credentials
 * 6. Generate and set authentication tokens as HTTP-only cookies
 * 7. Return user data and authentication status
 */
export async function POST(request: NextRequest) {
  const startTime = Date.now();

  try {
    // ============================================================================
    // STEP 1: Connect to database
    // ============================================================================
    await connectDB();

    // ============================================================================
    // STEP 2: Parse and validate request body
    // ============================================================================
    const { identifier, password, rememberMe } = await request.json();

    if (!identifier || !password) {
      return createBadRequestResponse(
        'Email/username and password are required.'
      );
    }

    // ============================================================================
    // STEP 3: Validate identifier format (email or username)
    // ============================================================================
    // Allow email-like patterns (even if used as username) and regular usernames
    const looksLikeEmail = /\S+@\S+\.\S+/.test(identifier);
    const isUsername =
      typeof identifier === 'string' &&
      identifier.trim().length >= 3;

    // Accept if it looks like an email OR is a valid username length
    // (Users with email as username should be able to login - they'll be prompted to change it)
    if (!(looksLikeEmail || isUsername)) {
      return createBadRequestResponse('Invalid identifier format.');
    }

    // ============================================================================
    // STEP 4: Extract client information (IP, user agent)
    // ============================================================================
    const ipAddress = getClientIP(request) || 'unknown';
    const userAgent = request.headers.get('user-agent') || 'unknown';

    // ============================================================================
    // STEP 5: Authenticate user credentials
    // ============================================================================
    const result = await authenticateUser(
      identifier,
      password,
      ipAddress,
      userAgent,
      rememberMe
    );

    if (!result.success) {
      return createErrorResponse(
        result.message || 'Authentication failed',
        401
      );
    }

    // Verify token exists
    if (!result.token) {
      console.error('❌ No token generated by authenticateUser!');
      return createServerErrorResponse(
        'Authentication failed - no token generated'
      );
    }

    // ============================================================================
    // STEP 6: Generate and set authentication tokens as HTTP-only cookies
    // ============================================================================
    const response = createSuccessResponse(
      {
        user: result.user,
        expiresAt: result.expiresAt,
        requiresPasswordUpdate: result.requiresPasswordUpdate ?? false,
        requiresProfileUpdate: result.requiresProfileUpdate ?? false,
        invalidProfileFields: result.invalidProfileFields,
        invalidProfileReasons: result.invalidProfileReasons,
      },
      'Login successful'
    );

    // Access token (7 days expiration)
    response.cookies.set('token', result.token!, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      path: '/',
      maxAge: 7 * 24 * 60 * 60, // 7 days (matches JWT expiration)
    });

    // Refresh token (30 days if rememberMe, otherwise 7 days)
    if (result.refreshToken) {
      response.cookies.set('refreshToken', result.refreshToken, {
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
        sameSite: 'lax',
        path: '/',
        maxAge: rememberMe ? 30 * 24 * 60 * 60 : 7 * 24 * 60 * 60, // 30 days or 7 days
      });
    }

    // ============================================================================
    // STEP 7: Return user data and authentication status
    // ============================================================================
    const duration = Date.now() - startTime;
    if (duration > 1000) {
      console.warn(`[Login API] Completed in ${duration}ms`);
    }

    return response;
  } catch (error) {
    const duration = Date.now() - startTime;
    console.error(`[Login API] Error after ${duration}ms:`, error);
    return createServerErrorResponse(
      getFriendlyErrorMessage(
        error instanceof Error ? error.message : 'Login failed'
      )
    );
  }
}
