export type MovementRequest = {
  _id: string;
  variance: number;
  previousBalance: number;
  currentBalance: number;
  amountToCollect: number;
  amountCollected: number;
  amountUncollected: number;
  partnerProfit: number;
  taxes: number;
  advance: number;
  locationName: string;
  locationFrom: string;
  locationTo: string;
  locationId: string;
  createdBy: string;
  movementType: string;
  installationType: string;
  reason: string;
  requestTo: string;
  cabinetIn: string;
  status: MovementRequestStatus;
  timestamp: Date;
  createdAt: Date;
  updatedAt: Date;
  __v?: number;
  approvedBy?: string;
  approvedBySecond?: string;
  deletedAt?: Date;
  locationFromId?: string;
  locationToId?: string;
  selectedMachines?: string[];
  recipientName?: string;
  creatorName?: string;
  machineDetails?: Array<{
    _id: string;
    serialNumber?: string;
    displayName: string;
  }>;
};

export type MovementRequestStatus = 'pending' | 'completed';
