import { verifyTOTPCode } from '@/app/api/lib/helpers/auth/totp';
import { getUserFromServer } from '@/app/api/lib/helpers/users/users';
import { connectDB } from '@/app/api/lib/middleware/db';
import UserModel from '@/app/api/lib/models/user';
import { NextRequest, NextResponse } from 'next/server';
import {
  logRouteUpdate,
  logRouteError,
  extractUserFromRequest,
} from '@/app/api/lib/utils/routeLogger';

/**
 * POST /api/auth/totp/confirm
 *
 * Verifies the first TOTP code from the authenticator app and activates 2FA for
 * the user. Called after setup or after a recovery flow to finalise the new secret.
 *
 * Body fields:
 * @param token         {string} Required. The 6-digit TOTP code generated by the authenticator app.
 * @param recoveryToken {string} Optional. A recovery token (from email) used to confirm setup
 *                               when no active session exists, e.g. during the recovery flow.
 */
export async function POST(req: NextRequest) {
  const startTime = Date.now();
  const functionName = 'POST /api/auth/totp/confirm';
  const user = extractUserFromRequest(req);

  try {
    const { token, recoveryToken } = await req.json();
    if (!token) {
      logRouteError(
        functionName,
        'POST',
        '/api/auth/totp/confirm',
        'Token is required',
        user
      );
      return NextResponse.json({ error: 'Token is required' }, { status: 400 });
    }

    const session = await getUserFromServer();

    await connectDB();
    let foundUser;

    if (session && session._id) {
      foundUser = await UserModel.findOne({ _id: session._id });
    } else if (recoveryToken) {
      // Allow confirmation via recovery token if no session exists
      foundUser = await UserModel.findOne({
        totpRecoveryToken: recoveryToken,
        totpRecoveryExpires: { $gt: new Date() },
      });
    }

    if (!foundUser) {
      logRouteError(
        functionName,
        'POST',
        '/api/auth/totp/confirm',
        session ? 'User not found' : 'Unauthorized or invalid recovery link',
        user
      );
      return NextResponse.json(
        {
          error: session
            ? 'User not found'
            : 'Unauthorized or invalid recovery link',
        },
        { status: session ? 404 : 401 }
      );
    }

    // ============================================================================
    // STEP 1: Determine which secret to verify against
    // 1. Recovery setup uses totpTempSecret
    // 2. Initial setup uses totpSecret (where totpEnabled is false)
    // ============================================================================
    const secretToVerify = foundUser.totpTempSecret || foundUser.totpSecret;

    if (!secretToVerify) {
      logRouteError(
        functionName,
        'POST',
        '/api/auth/totp/confirm',
        'Setup not initiated',
        user
      );
      return NextResponse.json(
        { error: 'Setup not initiated' },
        { status: 400 }
      );
    }

    const isValid = verifyTOTPCode(token, secretToVerify);
    if (isValid) {
      // ============================================================================
      // STEP 2: Promote temp secret to active secret if applicable
      // ============================================================================
      if (foundUser.totpTempSecret) {
        foundUser.totpSecret = foundUser.totpTempSecret;
        foundUser.totpTempSecret = null;
      }

      foundUser.totpEnabled = true;

      // ============================================================================
      // STEP 3: Clear recovery tokens
      // ============================================================================
      foundUser.totpRecoveryToken = null;
      foundUser.totpRecoveryExpires = null;

      await foundUser.save();

      const duration = Date.now() - startTime;
      logRouteUpdate(
        functionName,
        'POST',
        '/api/auth/totp/confirm',
        1,
        user,
        duration
      );

      return NextResponse.json({ success: true });
    } else {
      logRouteError(
        functionName,
        'POST',
        '/api/auth/totp/confirm',
        'Invalid authenticator code',
        user
      );
      return NextResponse.json(
        { error: 'Invalid authenticator code' },
        { status: 400 }
      );
    }
  } catch (error: unknown) {
    const errorMessage =
      error instanceof Error ? error.message : 'Internal server error';
    logRouteError(
      functionName,
      'POST',
      '/api/auth/totp/confirm',
      errorMessage,
      user
    );
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
