import { verifyTOTPCode } from '@/app/api/lib/helpers/auth/totp';
import { getUserFromServer } from '@/app/api/lib/helpers/users/users';
import { connectDB } from '@/app/api/lib/middleware/db';
import UserModel from '@/app/api/lib/models/user';
import { NextRequest, NextResponse } from 'next/server';

/**
 * POST /api/auth/totp/confirm
 *
 * Verifies the first TOTP code from the authenticator app and activates 2FA for
 * the user. Called after setup or after a recovery flow to finalise the new secret.
 *
 * Body fields:
 * @param token         {string} Required. The 6-digit TOTP code generated by the authenticator app.
 * @param recoveryToken {string} Optional. A recovery token (from email) used to confirm setup
 *                               when no active session exists, e.g. during the recovery flow.
 */
export async function POST(req: NextRequest) {
  try {
    const { token, recoveryToken } = await req.json();
    if (!token) {
      return NextResponse.json({ error: 'Token is required' }, { status: 400 });
    }

    const session = await getUserFromServer();

    await connectDB();
    let user;

    if (session && session._id) {
      user = await UserModel.findOne({ _id: session._id });
    } else if (recoveryToken) {
      // Allow confirmation via recovery token if no session exists
      user = await UserModel.findOne({
        totpRecoveryToken: recoveryToken,
        totpRecoveryExpires: { $gt: new Date() }
      });
    }

    if (!user) {
      return NextResponse.json({ error: session ? 'User not found' : 'Unauthorized or invalid recovery link' }, { status: session ? 404 : 401 });
    }

    // Determine which secret to verify against
    // 1. Recovery setup uses totpTempSecret
    // 2. Initial setup uses totpSecret (where totpEnabled is false)
    const secretToVerify = user.totpTempSecret || user.totpSecret;

    if (!secretToVerify) {
      return NextResponse.json({ error: 'Setup not initiated' }, { status: 400 });
    }

    const isValid = verifyTOTPCode(token, secretToVerify);
    if (isValid) {
      // If we verified a temp secret, promote it to the active secret
      if (user.totpTempSecret) {
        user.totpSecret = user.totpTempSecret;
        user.totpTempSecret = null;
      }

      user.totpEnabled = true;

      // Clear recovery tokens if they exist
      user.totpRecoveryToken = null;
      user.totpRecoveryExpires = null;

      await user.save();
      return NextResponse.json({ success: true });
    } else {
      return NextResponse.json({ error: 'Invalid authenticator code' }, { status: 400 });
    }
  } catch (error: unknown) {
    console.error('TOTP Confirm Error:', error instanceof Error ? error.message : error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
